language: java

addons:
  sonarcloud:
    organization: "mvallim"
    token: ${SONAR_TOKEN} 

cache:
  directories:
  - "$HOME/.cache"

script:
  - mvn clean compile

after_success:
  - mvn clean test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=java-fluent-validator

