language: java

addons:
  sonarcloud:
    organization: "mvallim"
    token:
      secure: "LUF1VEBcb4AUazFt723v9wdS9kwpd7H7r5Wz1Clo/x8WHb+UJc9fn6oiic8eV0nnJrD/BrOe634mbzRWA1LS+5de6Mtibp5IX7SMbACjlWLO8/C8pq1Tu7iSNUpHlehR2jF5pLSCbnHZNOTGclMTDSU6/gx0zaUzU2izvdikqHGfPMRWvcP6HjNj48RVhgRAObeNOuEAv6oSVmoI6Nw9237H97iTZ+TWV6Vz8Al+26l96kQYeIKE6TKsLV1dXt74LlmF01hjfmEcWLBZYd4ARDCt13qpann8wUUP77QioQAxVDDK3r5sSOIiXv9y0POskAKmNI0bv8QSveYdj0x7pDdqvlNzfDatVCiNZap6AMOAdfhWnKhfxl2CWBuoWbeLP+yx7RA86e3Rt0rIiAKMDvErGNK/WcbZwDYwszka1H960/KtEY4e3qCHUJjD9PymrHOcE197nA8VZzNz1VcwRIzZ1KXFERtCTjqg0VRIcL1IJDaGxyeNCnFF+mktQry4DkvNhEXZTiHgg+Ytjb2BMIccw1MJd3mERmyTrpWJbHMjI3P27/DP0T7avCMy7fPisCuU4VBZUtuaIax/W2UvWA+OAijTBa80rAGbGvian390MPPZNKBGxCh1c8FoqTc0BsBU9yv23Q2oP+nhz9C/OuvdrSmn2/brs4Pm+bEJreI="

cache:
  directories:
  - "$HOME/.cache"

script:
  - mvn clean compile
  - mvn test

install:
  - git fetch --unshallow

after_success:
  - mvn clean test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=java-fluent-validator

